// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");

var textBlack = Css.hex("565656");

var textBlackLight = Css.hex("4e4e4e");

var fontSizeLarge = Css.px(24);

var fontSizeNormal = Css.px(18);

var fontSizeSmall = Css.px(14);

var fontFamily = "'Lato', sans-serif";

exports.fontFamily = fontFamily;
exports.textBlack = textBlack;
exports.textBlackLight = textBlackLight;
exports.fontSizeLarge = fontSizeLarge;
exports.fontSizeNormal = fontSizeNormal;
exports.fontSizeSmall = fontSizeSmall;
/* textBlack Not a pure module */
