// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var CommonStyles$ReactTemplate = require("../constants/CommonStyles.bs.js");

var container = Css.style(/* :: */[
      Css.color(Css.white),
      /* :: */[
        Css.fontWeight(400),
        /* :: */[
          Css.fontSize(CommonStyles$ReactTemplate.fontSizeLarge),
          /* :: */[
            Css.flexGrow(0),
            /* :: */[
              Css.padding(Css.px(10)),
              /* :: */[
                Css.backgroundColor(Css.hex("50dffb")),
                /* :: */[
                  Css.borderBottom(Css.px(1), Css.solid, Css.hex("1bdbff")),
                  /* :: */[
                    Css.backgroundColor(Css.white),
                    /* :: */[
                      Css.padding(Css.px(10)),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var Style = /* module */[/* container */container];

var component = ReasonReact.statelessComponent("Header");

function make(title, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: container
                }, "" + (String(title) + ""));
    });
  return newrecord;
}

exports.Style = Style;
exports.component = component;
exports.make = make;
/* container Not a pure module */
