// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Page$ReactTemplate = require("./Page.bs.js");

var worker = new Worker("worker.js");

var msg = {
  text: "Hello world"
};

worker.postMessage(msg);

function msgBackHandler(e) {
  console.log("I am the main thread and I have received a message back from the worker:");
  console.log(e.data);
  return /* () */0;
}

worker.onmessage = msgBackHandler;

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Page$ReactTemplate.make("Dash", /* array */[])), "index");

exports.worker = worker;
exports.msg = msg;
exports.msgBackHandler = msgBackHandler;
/* worker Not a pure module */
