// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");

/* tuple */[
  Css.$$global("body", /* :: */[
        Css.margin(Css.px(0)),
        /* [] */0
      ]),
  Css.$$global("body", /* :: */[
        Css.backgroundColor(Css.rgb(255, 0, 0)),
        /* [] */0
      ])
];

/*  Not a pure module */
