// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

function parseChannels(stationList) {
  return $$Array.map((function (item) {
                var match = item.length;
                if (match !== 0) {
                  var itemSplit = item.split(",");
                  return /* record */[
                          /* name */Caml_array.caml_array_get(itemSplit, 0),
                          /* crsCode */Caml_array.caml_array_get(itemSplit, 1)
                        ];
                } else {
                  return /* record */[
                          /* name */"Invalid",
                          /* crsCode */"Invalid"
                        ];
                }
              }), $$Array.sub(stationList, 1, stationList.length - 2 | 0));
}

function fetchStationList(callback) {
  fetch("/assets/stations.csv").then((function (prim) {
            return prim.text();
          })).then((function (text) {
          var stories = parseChannels(text.split("\n"));
          Curry._1(callback, stories);
          return Promise.resolve(/* () */0);
        }));
  return /* () */0;
}

exports.parseChannels = parseChannels;
exports.fetchStationList = fetchStationList;
/* No side effect */
